function [coeffvals] = createFit(x_data, func_data, a_param)
%CREATEFIT(X,FUNC)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: func
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Apr-2021 14:14:39


%% Fit: 'untitled fit 1'.
% Some data - replace it with yours (its from an earlier project)
x = x_data';
y = func_data';
% Define Start points, fit-function and fit curve
x0 = [1 1 1]; 
fitfun = fittype( @(b,r,d,x) a_param + b*tanh(r*x + d) );
[fitted_curve,gof] = fit(x,y,fitfun,'StartPoint',x0)
% Save the coeffiecient values for a,b,c and d in a vector
coeffvals = coeffvalues(fitted_curve);
disp(num2str(coeffvals))

% Plot results
figure(2)
hold on
clf(figure(2))
scatter(x, y, 'r+')
hold on
plot(x,fitted_curve(x))
hold off


